# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('owner_name', models.CharField(max_length=50)),
            ],
        ),
    ]
