# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='administrator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boiska.Administrator'),
            preserve_default=False,
        ),
    ]
