# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0005_auto_20160911_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsground',
            name='name_prefix',
            field=models.CharField(blank=True, default='Boisko nr ', max_length=30),
        ),
    ]
