# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0006_sportsground_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsground',
            name='end_season_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sportsground',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sportsground',
            name='start_season_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
