# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0008_auto_20160912_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsground',
            name='name_prefix',
            field=models.CharField(blank=True, default='Boisko nr', max_length=30),
        ),
    ]
