# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0011_auto_20160913_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='administrator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
