# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0012_auto_20160917_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.AlterField(
            model_name='place',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
