# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0013_auto_20160917_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sportsground',
            unique_together=set([('place', 'name_prefix', 'local_id')]),
        ),
    ]
