# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiska', '0014_auto_20160918_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsground',
            options={'ordering': ['name_prefix', 'local_id']},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name may contain only letters, numbers, underscores and spaces.', regex='[\\w ]+')]),
        ),
    ]
